### ISSUE TITLE
PyTorch tensor size mismatch in train_csa.py?

### ISSUE THREAD

**Issue by jamieOverbeek** [JDACS4C-IMPROVE/Paccmann_MCA#10]
I'm not familiar with PyTorch, so I'm not sure how to interpret the following error:

```
Traceback (most recent call last):
  File "./train_csa.py", line 163, in <module>
    candle_main()
  File "./train_csa.py", line 160, in candle_main
    run(params)
  File "./train_csa.py", line 152, in run
    scores = main(params)
  File "/lambda_stor/homes/joverbeek/improve/Paccmann_MCA/train_paccmann.py", line 178, in main
    J = ckpt.restart(model)
  File "/homes/joverbeek/miniconda3/envs/paccmann_predictor/lib/python3.7/site-packages/candle/ckpt_utils.py", line 680, in restart
    self.build_model(model_file)
  File "/homes/joverbeek/miniconda3/envs/paccmann_predictor/lib/python3.7/site-packages/candle/ckpt_pytorch_utils.py", line 58, in build_model
    m.load_state_dict(checkpoint["model_state_dict"])
  File "/homes/joverbeek/miniconda3/envs/paccmann_predictor/lib/python3.7/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MCA:
	size mismatch for smiles_embedding.weight: copying a param with shape torch.Size([93, 16]) from checkpoint, the shape in current model is torch.Size([104, 16]).
```

**Comment by priyanka9991** [comment]
I fixed an issue with checkpointing. It should work fine now.
